# Weaver AI Configuration File Template
# TOML format configuration - template version for deployment
# Copy this to config.local.toml and add your actual API keys

[api_keys]
# GitHub API Token
# Get from: https://github.com/settings/tokens
github_token = "your_github_token_here"

# Slack Bot Token  
# Get from: https://api.slack.com/apps
slack_bot_token = "your_slack_bot_token_here"

# Google Gemini API Key
# Get from: https://makersuite.google.com/app/apikey
google_api_key = "your_google_api_key_here"

[repositories]
# Optional: GitHub Repository (format: owner/repo)
# Examples: microsoft/vscode, facebook/react, python/cpython
github_repo = "microsoft/vscode"

# Optional: Slack Channel IDs (comma-separated)
# slack_channels = ["C1234567890", "C0987654321"]

[database]
# Vector Database Settings
# Choose one of these options:

# Option 1: Relative path (current setting) - RECOMMENDED
vector_db_path = "./data/vector_db"

# Option 2: Absolute path
# vector_db_path = "C:\\Users\\konar\\OneDrive\\Desktop\\project1\\data\\vector_db"

# Option 3: Different directory name
# vector_db_path = "./data/chromadb"

# Option 4: System-wide location
# vector_db_path = "C:\\WeaverAI\\VectorDB"

[processing]
chunk_size = 500
chunk_overlap = 50

[api]
host = "127.0.0.1"
port = 8000

[environment]
# Environment type
env = "development"

# Debug mode
debug = true

# Logging level
log_level = "INFO"
